/*
 * Copyright (c) 2012-2013, Yunnan Yuan Xin technology Co., Ltd.
 * 
 * All rights reserved.
 */
package ass.management.admin.common.excel.model;

import java.io.Serializable;
import java.util.Date;

public class Dbxitem implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DCDBINFOID
     *
     * @mbggenerated
     */
    private String dcdbinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DBXZRUNIT
     *
     * @mbggenerated
     */
    private String dbxzrunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.WORKITEM
     *
     * @mbggenerated
     */
    private String workitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DBXBFQX
     *
     * @mbggenerated
     */
    private Date dbxbfqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DBXDBCYCLE
     *
     * @mbggenerated
     */
    private String dbxdbcycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.LASTBFDATE
     *
     * @mbggenerated
     */
    private Date lastbfdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DBXFINISHDATE
     *
     * @mbggenerated
     */
    private Date dbxfinishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DBMBFJID
     *
     * @mbggenerated
     */
    private String dbmbfjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DBXSEQUENCE
     *
     * @mbggenerated
     */
    private String dbxsequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DBXZRUNITNAME
     *
     * @mbggenerated
     */
    private String dbxzrunitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.SCHEDUL
     *
     * @mbggenerated
     */
    private String schedul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.DBXBZ
     *
     * @mbggenerated
     */
    private String dbxbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_DBXITEM.SORT
     *
     * @mbggenerated
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_APPDCDB_LX_DBXITEM
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.ID
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.ID
     *
     * @param id the value for T_APPDCDB_LX_DBXITEM.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DCDBINFOID
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DCDBINFOID
     *
     * @mbggenerated
     */
    public String getDcdbinfoid() {
        return dcdbinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DCDBINFOID
     *
     * @param dcdbinfoid the value for T_APPDCDB_LX_DBXITEM.DCDBINFOID
     *
     * @mbggenerated
     */
    public void setDcdbinfoid(String dcdbinfoid) {
        this.dcdbinfoid = dcdbinfoid == null ? null : dcdbinfoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DBXZRUNIT
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DBXZRUNIT
     *
     * @mbggenerated
     */
    public String getDbxzrunit() {
        return dbxzrunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DBXZRUNIT
     *
     * @param dbxzrunit the value for T_APPDCDB_LX_DBXITEM.DBXZRUNIT
     *
     * @mbggenerated
     */
    public void setDbxzrunit(String dbxzrunit) {
        this.dbxzrunit = dbxzrunit == null ? null : dbxzrunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.WORKITEM
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.WORKITEM
     *
     * @mbggenerated
     */
    public String getWorkitem() {
        return workitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.WORKITEM
     *
     * @param workitem the value for T_APPDCDB_LX_DBXITEM.WORKITEM
     *
     * @mbggenerated
     */
    public void setWorkitem(String workitem) {
        this.workitem = workitem == null ? null : workitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DBXBFQX
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DBXBFQX
     *
     * @mbggenerated
     */
    public Date getDbxbfqx() {
        return dbxbfqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DBXBFQX
     *
     * @param dbxbfqx the value for T_APPDCDB_LX_DBXITEM.DBXBFQX
     *
     * @mbggenerated
     */
    public void setDbxbfqx(Date dbxbfqx) {
        this.dbxbfqx = dbxbfqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DBXDBCYCLE
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DBXDBCYCLE
     *
     * @mbggenerated
     */
    public String getDbxdbcycle() {
        return dbxdbcycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DBXDBCYCLE
     *
     * @param dbxdbcycle the value for T_APPDCDB_LX_DBXITEM.DBXDBCYCLE
     *
     * @mbggenerated
     */
    public void setDbxdbcycle(String dbxdbcycle) {
        this.dbxdbcycle = dbxdbcycle == null ? null : dbxdbcycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.LASTBFDATE
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.LASTBFDATE
     *
     * @mbggenerated
     */
    public Date getLastbfdate() {
        return lastbfdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.LASTBFDATE
     *
     * @param lastbfdate the value for T_APPDCDB_LX_DBXITEM.LASTBFDATE
     *
     * @mbggenerated
     */
    public void setLastbfdate(Date lastbfdate) {
        this.lastbfdate = lastbfdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DBXFINISHDATE
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DBXFINISHDATE
     *
     * @mbggenerated
     */
    public Date getDbxfinishdate() {
        return dbxfinishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DBXFINISHDATE
     *
     * @param dbxfinishdate the value for T_APPDCDB_LX_DBXITEM.DBXFINISHDATE
     *
     * @mbggenerated
     */
    public void setDbxfinishdate(Date dbxfinishdate) {
        this.dbxfinishdate = dbxfinishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.STATUS
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.STATUS
     *
     * @param status the value for T_APPDCDB_LX_DBXITEM.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DBMBFJID
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DBMBFJID
     *
     * @mbggenerated
     */
    public String getDbmbfjid() {
        return dbmbfjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DBMBFJID
     *
     * @param dbmbfjid the value for T_APPDCDB_LX_DBXITEM.DBMBFJID
     *
     * @mbggenerated
     */
    public void setDbmbfjid(String dbmbfjid) {
        this.dbmbfjid = dbmbfjid == null ? null : dbmbfjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DBXSEQUENCE
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DBXSEQUENCE
     *
     * @mbggenerated
     */
    public String getDbxsequence() {
        return dbxsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DBXSEQUENCE
     *
     * @param dbxsequence the value for T_APPDCDB_LX_DBXITEM.DBXSEQUENCE
     *
     * @mbggenerated
     */
    public void setDbxsequence(String dbxsequence) {
        this.dbxsequence = dbxsequence == null ? null : dbxsequence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DBXZRUNITNAME
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DBXZRUNITNAME
     *
     * @mbggenerated
     */
    public String getDbxzrunitname() {
        return dbxzrunitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DBXZRUNITNAME
     *
     * @param dbxzrunitname the value for T_APPDCDB_LX_DBXITEM.DBXZRUNITNAME
     *
     * @mbggenerated
     */
    public void setDbxzrunitname(String dbxzrunitname) {
        this.dbxzrunitname = dbxzrunitname == null ? null : dbxzrunitname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.SCHEDUL
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.SCHEDUL
     *
     * @mbggenerated
     */
    public String getSchedul() {
        return schedul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.SCHEDUL
     *
     * @param schedul the value for T_APPDCDB_LX_DBXITEM.SCHEDUL
     *
     * @mbggenerated
     */
    public void setSchedul(String schedul) {
        this.schedul = schedul == null ? null : schedul.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.DBXBZ
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.DBXBZ
     *
     * @mbggenerated
     */
    public String getDbxbz() {
        return dbxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.DBXBZ
     *
     * @param dbxbz the value for T_APPDCDB_LX_DBXITEM.DBXBZ
     *
     * @mbggenerated
     */
    public void setDbxbz(String dbxbz) {
        this.dbxbz = dbxbz == null ? null : dbxbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_DBXITEM.SORT
     *
     * @return the value of T_APPDCDB_LX_DBXITEM.SORT
     *
     * @mbggenerated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_DBXITEM.SORT
     *
     * @param sort the value for T_APPDCDB_LX_DBXITEM.SORT
     *
     * @mbggenerated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }
}
