/*
 * Copyright (c) 2012-2013, Yunnan Yuan Xin technology Co., Ltd.
 * 
 * All rights reserved.
 */
package ass.management.admin.common.excel.model;

import java.io.Serializable;
import java.util.Date;

public class DcdbFkInfoItem implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.FKINFOID
     *
     * @mbggenerated
     */
    private String fkInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.SITUATEDESCRIPT
     *
     * @mbggenerated
     */
    private String situateDescript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.FKSTATUS
     *
     * @mbggenerated
     */
    private String fkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.FINISHTIME
     *
     * @mbggenerated
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.WORKCONT
     *
     * @mbggenerated
     */
    private String workCont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.TROUBLEANDSOLV
     *
     * @mbggenerated
     */
    private String troubleAndSolv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.NEXTWORK
     *
     * @mbggenerated
     */
    private String nextWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.AUDITOR
     *
     * @mbggenerated
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.SHSTATU
     *
     * @mbggenerated
     */
    private String shStatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.DCSYJ
     *
     * @mbggenerated
     */
    private String dcsYj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.TBR
     *
     * @mbggenerated
     */
    private String tbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.TBRCODE
     *
     * @mbggenerated
     */
    private String tbrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.GZMBFJID
     *
     * @mbggenerated
     */
    private String gzMbfjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.DBXITEMID
     *
     * @mbggenerated
     */
    private String dbxItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.CURPROGRESS
     *
     * @mbggenerated
     */
    private String curProgress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.SORT
     *
     * @mbggenerated
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_FK_ITEM.TBDATE
     *
     * @mbggenerated
     */
    private Date tbdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_APPDCDB_FK_ITEM
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.ID
     *
     * @return the value of T_APPDCDB_FK_ITEM.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.ID
     *
     * @param id the value for T_APPDCDB_FK_ITEM.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.FKINFOID
     *
     * @return the value of T_APPDCDB_FK_ITEM.FKINFOID
     *
     * @mbggenerated
     */
    public String getFkInfoId() {
        return fkInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.FKINFOID
     *
     * @param fkInfoId the value for T_APPDCDB_FK_ITEM.FKINFOID
     *
     * @mbggenerated
     */
    public void setFkInfoId(String fkInfoId) {
        this.fkInfoId = fkInfoId == null ? null : fkInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.SITUATEDESCRIPT
     *
     * @return the value of T_APPDCDB_FK_ITEM.SITUATEDESCRIPT
     *
     * @mbggenerated
     */
    public String getSituateDescript() {
        return situateDescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.SITUATEDESCRIPT
     *
     * @param situateDescript the value for T_APPDCDB_FK_ITEM.SITUATEDESCRIPT
     *
     * @mbggenerated
     */
    public void setSituateDescript(String situateDescript) {
        this.situateDescript = situateDescript == null ? null : situateDescript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.FKSTATUS
     *
     * @return the value of T_APPDCDB_FK_ITEM.FKSTATUS
     *
     * @mbggenerated
     */
    public String getFkStatus() {
        return fkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.FKSTATUS
     *
     * @param fkStatus the value for T_APPDCDB_FK_ITEM.FKSTATUS
     *
     * @mbggenerated
     */
    public void setFkStatus(String fkStatus) {
        this.fkStatus = fkStatus == null ? null : fkStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.FINISHTIME
     *
     * @return the value of T_APPDCDB_FK_ITEM.FINISHTIME
     *
     * @mbggenerated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.FINISHTIME
     *
     * @param finishTime the value for T_APPDCDB_FK_ITEM.FINISHTIME
     *
     * @mbggenerated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.WORKCONT
     *
     * @return the value of T_APPDCDB_FK_ITEM.WORKCONT
     *
     * @mbggenerated
     */
    public String getWorkCont() {
        return workCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.WORKCONT
     *
     * @param workCont the value for T_APPDCDB_FK_ITEM.WORKCONT
     *
     * @mbggenerated
     */
    public void setWorkCont(String workCont) {
        this.workCont = workCont == null ? null : workCont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.TROUBLEANDSOLV
     *
     * @return the value of T_APPDCDB_FK_ITEM.TROUBLEANDSOLV
     *
     * @mbggenerated
     */
    public String getTroubleAndSolv() {
        return troubleAndSolv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.TROUBLEANDSOLV
     *
     * @param troubleAndSolv the value for T_APPDCDB_FK_ITEM.TROUBLEANDSOLV
     *
     * @mbggenerated
     */
    public void setTroubleAndSolv(String troubleAndSolv) {
        this.troubleAndSolv = troubleAndSolv == null ? null : troubleAndSolv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.NEXTWORK
     *
     * @return the value of T_APPDCDB_FK_ITEM.NEXTWORK
     *
     * @mbggenerated
     */
    public String getNextWork() {
        return nextWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.NEXTWORK
     *
     * @param nextWork the value for T_APPDCDB_FK_ITEM.NEXTWORK
     *
     * @mbggenerated
     */
    public void setNextWork(String nextWork) {
        this.nextWork = nextWork == null ? null : nextWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.AUDITOR
     *
     * @return the value of T_APPDCDB_FK_ITEM.AUDITOR
     *
     * @mbggenerated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.AUDITOR
     *
     * @param auditor the value for T_APPDCDB_FK_ITEM.AUDITOR
     *
     * @mbggenerated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.SHSTATU
     *
     * @return the value of T_APPDCDB_FK_ITEM.SHSTATU
     *
     * @mbggenerated
     */
    public String getShStatu() {
        return shStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.SHSTATU
     *
     * @param shStatu the value for T_APPDCDB_FK_ITEM.SHSTATU
     *
     * @mbggenerated
     */
    public void setShStatu(String shStatu) {
        this.shStatu = shStatu == null ? null : shStatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.DCSYJ
     *
     * @return the value of T_APPDCDB_FK_ITEM.DCSYJ
     *
     * @mbggenerated
     */
    public String getDcsYj() {
        return dcsYj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.DCSYJ
     *
     * @param dcsYj the value for T_APPDCDB_FK_ITEM.DCSYJ
     *
     * @mbggenerated
     */
    public void setDcsYj(String dcsYj) {
        this.dcsYj = dcsYj == null ? null : dcsYj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.TBR
     *
     * @return the value of T_APPDCDB_FK_ITEM.TBR
     *
     * @mbggenerated
     */
    public String getTbr() {
        return tbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.TBR
     *
     * @param tbr the value for T_APPDCDB_FK_ITEM.TBR
     *
     * @mbggenerated
     */
    public void setTbr(String tbr) {
        this.tbr = tbr == null ? null : tbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.TBRCODE
     *
     * @return the value of T_APPDCDB_FK_ITEM.TBRCODE
     *
     * @mbggenerated
     */
    public String getTbrCode() {
        return tbrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.TBRCODE
     *
     * @param tbrCode the value for T_APPDCDB_FK_ITEM.TBRCODE
     *
     * @mbggenerated
     */
    public void setTbrCode(String tbrCode) {
        this.tbrCode = tbrCode == null ? null : tbrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.GZMBFJID
     *
     * @return the value of T_APPDCDB_FK_ITEM.GZMBFJID
     *
     * @mbggenerated
     */
    public String getGzMbfjId() {
        return gzMbfjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.GZMBFJID
     *
     * @param gzMbfjId the value for T_APPDCDB_FK_ITEM.GZMBFJID
     *
     * @mbggenerated
     */
    public void setGzMbfjId(String gzMbfjId) {
        this.gzMbfjId = gzMbfjId == null ? null : gzMbfjId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.DBXITEMID
     *
     * @return the value of T_APPDCDB_FK_ITEM.DBXITEMID
     *
     * @mbggenerated
     */
    public String getDbxItemId() {
        return dbxItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.DBXITEMID
     *
     * @param dbxItemId the value for T_APPDCDB_FK_ITEM.DBXITEMID
     *
     * @mbggenerated
     */
    public void setDbxItemId(String dbxItemId) {
        this.dbxItemId = dbxItemId == null ? null : dbxItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.CURPROGRESS
     *
     * @return the value of T_APPDCDB_FK_ITEM.CURPROGRESS
     *
     * @mbggenerated
     */
    public String getCurProgress() {
        return curProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.CURPROGRESS
     *
     * @param curProgress the value for T_APPDCDB_FK_ITEM.CURPROGRESS
     *
     * @mbggenerated
     */
    public void setCurProgress(String curProgress) {
        this.curProgress = curProgress == null ? null : curProgress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.SORT
     *
     * @return the value of T_APPDCDB_FK_ITEM.SORT
     *
     * @mbggenerated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.SORT
     *
     * @param sort the value for T_APPDCDB_FK_ITEM.SORT
     *
     * @mbggenerated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_FK_ITEM.TBDATE
     *
     * @return the value of T_APPDCDB_FK_ITEM.TBDATE
     *
     * @mbggenerated
     */
    public Date getTbdate() {
        return tbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_FK_ITEM.TBDATE
     *
     * @param tbdate the value for T_APPDCDB_FK_ITEM.TBDATE
     *
     * @mbggenerated
     */
    public void setTbdate(Date tbdate) {
        this.tbdate = tbdate;
    }
}
