/*
 * Copyright (c) 2012-2013, Yunnan Yuan Xin technology Co., Ltd.
 * 
 * All rights reserved.
 */
package ass.management.admin.common.excel.model;

import java.io.Serializable;
import java.util.Date;

public class Dcdbgzmbfj implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.DCDBINFOID
     *
     * @mbggenerated
     */
    private String dcdbinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.BFQX
     *
     * @mbggenerated
     */
    private Date bfqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.ZRUNITCODE
     *
     * @mbggenerated
     */
    private String zrunitcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.ZRZCODE
     *
     * @mbggenerated
     */
    private String zrzcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.ZRZNAME
     *
     * @mbggenerated
     */
    private String zrzname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.ZRZPHONE
     *
     * @mbggenerated
     */
    private String zrzphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.WORKTARGET
     *
     * @mbggenerated
     */
    private String worktarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.DBXSTATUS
     *
     * @mbggenerated
     */
    private String dbxstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.ZRUNITNAME
     *
     * @mbggenerated
     */
    private String zrunitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.XBUNITCODE
     *
     * @mbggenerated
     */
    private String xbunitcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.XBUNITNAME
     *
     * @mbggenerated
     */
    private String xbunitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.MBFJDSEQ
     *
     * @mbggenerated
     */
    private String mbfjdseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.SORT
     *
     * @mbggenerated
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.DONEEXECUTE
     *
     * @mbggenerated
     */
    private String doneexecute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.REMINDSTATUS
     *
     * @mbggenerated
     */
    private String remindstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.DONEEXECUTEDETAIL
     *
     * @mbggenerated
     */
    private String doneexecutedetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.BUSINESSAREA
     *
     * @mbggenerated
     */
    private String businessarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APPDCDB_LX_GZMBFJ.FKQS
     *
     * @mbggenerated
     */
    private Integer fkqs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_APPDCDB_LX_GZMBFJ
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.ID
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.ID
     *
     * @param id the value for T_APPDCDB_LX_GZMBFJ.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.DCDBINFOID
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.DCDBINFOID
     *
     * @mbggenerated
     */
    public String getDcdbinfoid() {
        return dcdbinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.DCDBINFOID
     *
     * @param dcdbinfoid the value for T_APPDCDB_LX_GZMBFJ.DCDBINFOID
     *
     * @mbggenerated
     */
    public void setDcdbinfoid(String dcdbinfoid) {
        this.dcdbinfoid = dcdbinfoid == null ? null : dcdbinfoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.BFQX
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.BFQX
     *
     * @mbggenerated
     */
    public Date getBfqx() {
        return bfqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.BFQX
     *
     * @param bfqx the value for T_APPDCDB_LX_GZMBFJ.BFQX
     *
     * @mbggenerated
     */
    public void setBfqx(Date bfqx) {
        this.bfqx = bfqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.BZ
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.BZ
     *
     * @param bz the value for T_APPDCDB_LX_GZMBFJ.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.ZRUNITCODE
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.ZRUNITCODE
     *
     * @mbggenerated
     */
    public String getZrunitcode() {
        return zrunitcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.ZRUNITCODE
     *
     * @param zrunitcode the value for T_APPDCDB_LX_GZMBFJ.ZRUNITCODE
     *
     * @mbggenerated
     */
    public void setZrunitcode(String zrunitcode) {
        this.zrunitcode = zrunitcode == null ? null : zrunitcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.ZRZCODE
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.ZRZCODE
     *
     * @mbggenerated
     */
    public String getZrzcode() {
        return zrzcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.ZRZCODE
     *
     * @param zrzcode the value for T_APPDCDB_LX_GZMBFJ.ZRZCODE
     *
     * @mbggenerated
     */
    public void setZrzcode(String zrzcode) {
        this.zrzcode = zrzcode == null ? null : zrzcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.ZRZNAME
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.ZRZNAME
     *
     * @mbggenerated
     */
    public String getZrzname() {
        return zrzname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.ZRZNAME
     *
     * @param zrzname the value for T_APPDCDB_LX_GZMBFJ.ZRZNAME
     *
     * @mbggenerated
     */
    public void setZrzname(String zrzname) {
        this.zrzname = zrzname == null ? null : zrzname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.ZRZPHONE
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.ZRZPHONE
     *
     * @mbggenerated
     */
    public String getZrzphone() {
        return zrzphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.ZRZPHONE
     *
     * @param zrzphone the value for T_APPDCDB_LX_GZMBFJ.ZRZPHONE
     *
     * @mbggenerated
     */
    public void setZrzphone(String zrzphone) {
        this.zrzphone = zrzphone == null ? null : zrzphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.WORKTARGET
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.WORKTARGET
     *
     * @mbggenerated
     */
    public String getWorktarget() {
        return worktarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.WORKTARGET
     *
     * @param worktarget the value for T_APPDCDB_LX_GZMBFJ.WORKTARGET
     *
     * @mbggenerated
     */
    public void setWorktarget(String worktarget) {
        this.worktarget = worktarget == null ? null : worktarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.DBXSTATUS
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.DBXSTATUS
     *
     * @mbggenerated
     */
    public String getDbxstatus() {
        return dbxstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.DBXSTATUS
     *
     * @param dbxstatus the value for T_APPDCDB_LX_GZMBFJ.DBXSTATUS
     *
     * @mbggenerated
     */
    public void setDbxstatus(String dbxstatus) {
        this.dbxstatus = dbxstatus == null ? null : dbxstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.ZRUNITNAME
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.ZRUNITNAME
     *
     * @mbggenerated
     */
    public String getZrunitname() {
        return zrunitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.ZRUNITNAME
     *
     * @param zrunitname the value for T_APPDCDB_LX_GZMBFJ.ZRUNITNAME
     *
     * @mbggenerated
     */
    public void setZrunitname(String zrunitname) {
        this.zrunitname = zrunitname == null ? null : zrunitname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.XBUNITCODE
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.XBUNITCODE
     *
     * @mbggenerated
     */
    public String getXbunitcode() {
        return xbunitcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.XBUNITCODE
     *
     * @param xbunitcode the value for T_APPDCDB_LX_GZMBFJ.XBUNITCODE
     *
     * @mbggenerated
     */
    public void setXbunitcode(String xbunitcode) {
        this.xbunitcode = xbunitcode == null ? null : xbunitcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.XBUNITNAME
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.XBUNITNAME
     *
     * @mbggenerated
     */
    public String getXbunitname() {
        return xbunitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.XBUNITNAME
     *
     * @param xbunitname the value for T_APPDCDB_LX_GZMBFJ.XBUNITNAME
     *
     * @mbggenerated
     */
    public void setXbunitname(String xbunitname) {
        this.xbunitname = xbunitname == null ? null : xbunitname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.MBFJDSEQ
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.MBFJDSEQ
     *
     * @mbggenerated
     */
    public String getMbfjdseq() {
        return mbfjdseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.MBFJDSEQ
     *
     * @param mbfjdseq the value for T_APPDCDB_LX_GZMBFJ.MBFJDSEQ
     *
     * @mbggenerated
     */
    public void setMbfjdseq(String mbfjdseq) {
        this.mbfjdseq = mbfjdseq == null ? null : mbfjdseq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.SORT
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.SORT
     *
     * @mbggenerated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.SORT
     *
     * @param sort the value for T_APPDCDB_LX_GZMBFJ.SORT
     *
     * @mbggenerated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.DONEEXECUTE
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.DONEEXECUTE
     *
     * @mbggenerated
     */
    public String getDoneexecute() {
        return doneexecute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.DONEEXECUTE
     *
     * @param doneexecute the value for T_APPDCDB_LX_GZMBFJ.DONEEXECUTE
     *
     * @mbggenerated
     */
    public void setDoneexecute(String doneexecute) {
        this.doneexecute = doneexecute == null ? null : doneexecute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.REMINDSTATUS
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.REMINDSTATUS
     *
     * @mbggenerated
     */
    public String getRemindstatus() {
        return remindstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.REMINDSTATUS
     *
     * @param remindstatus the value for T_APPDCDB_LX_GZMBFJ.REMINDSTATUS
     *
     * @mbggenerated
     */
    public void setRemindstatus(String remindstatus) {
        this.remindstatus = remindstatus == null ? null : remindstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.DONEEXECUTEDETAIL
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.DONEEXECUTEDETAIL
     *
     * @mbggenerated
     */
    public String getDoneexecutedetail() {
        return doneexecutedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.DONEEXECUTEDETAIL
     *
     * @param doneexecutedetail the value for T_APPDCDB_LX_GZMBFJ.DONEEXECUTEDETAIL
     *
     * @mbggenerated
     */
    public void setDoneexecutedetail(String doneexecutedetail) {
        this.doneexecutedetail = doneexecutedetail == null ? null : doneexecutedetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.BUSINESSAREA
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.BUSINESSAREA
     *
     * @mbggenerated
     */
    public String getBusinessarea() {
        return businessarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.BUSINESSAREA
     *
     * @param businessarea the value for T_APPDCDB_LX_GZMBFJ.BUSINESSAREA
     *
     * @mbggenerated
     */
    public void setBusinessarea(String businessarea) {
        this.businessarea = businessarea == null ? null : businessarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APPDCDB_LX_GZMBFJ.FKQS
     *
     * @return the value of T_APPDCDB_LX_GZMBFJ.FKQS
     *
     * @mbggenerated
     */
    public Integer getFkqs() {
        return fkqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APPDCDB_LX_GZMBFJ.FKQS
     *
     * @param fkqs the value for T_APPDCDB_LX_GZMBFJ.FKQS
     *
     * @mbggenerated
     */
    public void setFkqs(Integer fkqs) {
        this.fkqs = fkqs;
    }
}
